# -*- coding: utf-8 -*-
"""1-temelosıntaracıpython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bmb68KfCfYIa5Ej098udCWX0hSc-ZXDv
"""

import requests

def check_username(username):
    platforms = {
        "GitHub": f"https://github.com/{username}",
        "Twitter": f"https://twitter.com/{username}",
        "Reddit": f"https://www.reddit.com/user/{username}",
    }

    for site, url in platforms.items():
        try:
            response = requests.get(url)
            if response.status_code == 200:
                print(f"[+] {site} profil bulundu: {url}")
            else:
                print(f"[-] {site} profil yok: {url}")
        except requests.RequestException:
            print(f"[!] {site} için bağlantı hatası")

if __name__ == "__main__":
    user = input("Kullanıcı adı gir: ")
    check_username(user)

